const l = (tr: string, en: string) => ({ tr, en }) as const;

export type CapabilityGroupId = "general" | "finance" | "manufacturing" | "textile" | "plastics";

export const capabilityCatalogCopy = {
  eyebrow: l("Dima yetenekleri", "Dima capabilities"),
  title: l("Tek bir şirket zekâsı, onlarca gerçek karar problemi.", "One company intelligence layer, dozens of real decision problems."),
  intro: l(
    "Her yetenek aynı Dima döngüsünü kullanır. Şirket bağlamını izler, önemli değişimi fark eder, nedenini araştırır, seçenek hazırlar ve sonucu hafızaya bağlar.",
    "Every capability uses the same Dima loop. It watches company context, detects meaningful change, investigates why, prepares options and connects outcomes back to memory."
  ),
  search: l("Yetenek ara", "Search capabilities"),
  all: l("Tümü", "All"),
  featured: l("Öne çıkan yetenekler", "Featured capabilities"),
  viewAll: l("Tüm kullanım alanlarını görün", "Explore all use cases"),
  labels: {
    watches: l("Ne üzerinde çalışır?", "What does it work on?"),
    outcome: l("İş çıktısı", "Business outcome"),
    loop: l("Aynı Dima döngüsü", "The same Dima loop"),
  },
  loop: {
    tr: ["İzler", "Fark eder", "Araştırır", "Optimize eder", "Karara taşır", "Hatırlar"],
    en: ["Monitors", "Detects", "Investigates", "Optimizes", "Prepares decisions", "Remembers"],
  },
} as const;

export const capabilityGroups = [
  { id: "general", label: l("Şirket zekâsı", "Company intelligence"), description: l("Kurulumdan karar hafızasına kadar Dima'nın ortak ürün yetenekleri.", "Shared Dima capabilities from setup through decision memory.") },
  { id: "finance", label: l("Muhasebe ve finans", "Accounting & finance"), description: l("Nakit, tahsilat, ödeme, mutabakat, marj, bütçe ve karar akışları.", "Cash, collections, payments, reconciliation, margin, budget and decision flows.") },
  { id: "manufacturing", label: l("Üretim", "Manufacturing"), description: l("Tesis durumu, OEE, kayıp, kapasite, kalite, bakım, enerji ve teslim.", "Plant state, OEE, loss, capacity, quality, maintenance, energy and delivery.") },
  { id: "textile", label: l("Tekstil ve boya", "Textile & dyeing"), description: l("Reçete, renk, parti, makine, kaynak tüketimi ve kalite bağlamı.", "Recipe, shade, batch, machine, resource use and quality context.") },
  { id: "plastics", label: l("Plastik işleme", "Plastics processing"), description: l("Malzeme, proses, çevrim, kalıp, fire, enerji ve birim maliyet.", "Material, process, cycle, mold, scrap, energy and unit cost.") },
] as const;

export const capabilities = [
  { id:"smart-setup", group:"general", title:l("Akıllı kurulum ve veri bağlama","Smart setup and data connection"), summary:l("Veritabanı, Excel/CSV ve diğer kaynakları bağlar; şemayı şirket varlıklarına dönüştürmek için yönlendirir.","Connects databases, spreadsheets and other sources, then guides schema-to-business mapping."), outcome:l("İlk Şirket Haritası ve doğrulanmış veri kapsamı","First Company Map with validated data coverage") },
  { id:"sector-context", group:"general", title:l("Sektör zekâsı ve şirket uyarlaması","Sector intelligence and company overlay"), summary:l("Sektörün kavramlarını başlangıç bağlamı olarak getirir ve şirketin gerçek işleyişine göre düzeltir.","Starts with sector concepts and adapts them to how the company actually operates."), outcome:l("Şirkete özel varlıklar, ilişkiler ve ölçüler","Company-specific entities, relationships and measures") },
  { id:"today", group:"general", title:l("Dima Bugün","Dima Today"), summary:l("Günün gerçekten dikkat gerektiren sinyal, fırsat, araştırma ve kararlarını tek öncelik kuyruğunda toplar.","Ranks the signals, opportunities, investigations and decisions that actually need attention today."), outcome:l("Yönetici için önceliklendirilmiş gündem","A prioritized executive agenda") },
  { id:"watch", group:"general", title:l("Radar ve izleme","Radar and watch"), summary:l("Plan, eşik, örüntü, varlık değişimi ve karar varsayımlarını kullanıcı sormadan sürekli kontrol eder.","Continuously checks plans, thresholds, patterns, entity changes and decision assumptions without waiting for a question."), outcome:l("Erken sinyal ve proaktif uyarı","Early signals and proactive alerts") },
  { id:"evidence", group:"general", title:l("Kanıt paneli","Evidence panel"), summary:l("Her önemli rakam ve bulguyu kaynak, dönem, filtre, tazelik ve hesap bağlamıyla birlikte gösterir.","Keeps every important number and finding attached to source, period, filter, freshness and calculation context."), outcome:l("Denetlenebilir bulgu ve güvenilir sayı","Auditable findings and trustworthy numbers") },
  { id:"contextual-ask", group:"general", title:l("Bağlamsal soru","Contextual ask"), summary:l("Seçili müşteri, makine, sinyal veya araştırma bağlamını kaybetmeden doğal dille derinleşir.","Lets users ask naturally without losing the selected customer, machine, signal or investigation context."), outcome:l("Aynı bağlamda açıklama, grafik ve takip","Explanation, chart and follow-up in the same context") },
  { id:"investigation", group:"general", title:l("Araştırma alanı","Investigation workspace"), summary:l("Bir sinyalin kırılımlarını, ilişkilerini, geçmiş karşılaştırmalarını ve neden adaylarını tek çalışma alanında toplar.","Combines breakdowns, relationships, historical comparisons and cause candidates for one signal."), outcome:l("Kanıtlı neden adayları","Evidence-backed cause candidates") },
  { id:"root-cause-room", group:"general", title:l("İş alanı kök neden alanı","Domain root-cause room"), summary:l("Finans, üretim ve diğer alanlarda aynı araştırma motorunu o alanın gerçek ölçü ve ilişkileriyle çalıştırır.","Runs the same investigation engine with the real measures and relationships of each business domain."), outcome:l("Alan bağlamına özel neden zinciri","Domain-specific cause chain") },
  { id:"live-analysis", group:"general", title:l("Canlı analiz ve kaydedilmiş görünüm","Live analysis and saved view"), summary:l("Grafik ve analizleri yalnız izlenen ekranlar olmaktan çıkarıp izleme, açıklama, araştırma ve karar akışlarına bağlar.","Turns charts and analyses into starting points for monitoring, explanation, investigation and decisions."), outcome:l("Yaşayan ve tekrar kullanılabilir analiz","Living, reusable analysis") },
  { id:"morning-brief", group:"general", title:l("Sabah özeti","Morning briefing"), summary:l("Kullanıcı uygulamayı açmadan dün ne değişti, bugün ne önemli ve hangi karar bekliyor sorularını özetler.","Summarizes what changed, what matters today and which decisions are waiting before the user opens the app."), outcome:l("30 saniyelik yönetim özeti","A 30-second management brief") },
  { id:"decision-desk", group:"general", title:l("Karar Masası","Decision Desk"), summary:l("Amaç, seçenek, ölçüt, kısıt, kanıt ve varsayımları tek karar nesnesinde bir araya getirir.","Brings objective, options, criteria, constraints, evidence and assumptions into one decision object."), outcome:l("Karşılaştırılabilir karar seçenekleri","Comparable decision options") },
  { id:"scenario-studio", group:"general", title:l("Senaryo alanı","Scenario studio"), summary:l("Fiyat, talep, vardiya, maliyet veya kapasite gibi varsayımlar değiştiğinde sonucu yeniden hesaplar.","Recalculates outcomes when assumptions such as price, demand, shifts, cost or capacity change."), outcome:l("Ne olursa ne olur görünümü","What-if impact view") },
  { id:"controlled-action", group:"general", title:l("Kontrollü eylem ve onay","Governed action and approval"), summary:l("Görev, e-posta, iş emri veya sistem kaydı gibi adımları taslak, doğrulama, önizleme, onay ve kayıt iziyle yönetir.","Manages tasks, messages, work orders or system records through draft, validation, preview, approval and receipt."), outcome:l("Yetkili ve izlenebilir uygulama","Authorized and traceable execution") },
  { id:"outcome-memory", group:"general", title:l("Sonuç takibi ve karar hafızası","Outcome tracking and decision memory"), summary:l("Karardan sonra beklenen ile gerçekleşeni karşılaştırır ve sonucu sonraki benzer kararlarda yeniden kullanır.","Compares expected and actual outcomes, then reuses the result in future similar decisions."), outcome:l("Kurumsal karar hafızası","Institutional decision memory") },
  { id:"agenda", group:"general", title:l("Dima Gündemi","Dima Agenda"), summary:l("Yönetimin bugün sorması gereken soruları sinyal, hedef ve açık kararlardan kendisi çıkarır.","Derives the questions management should ask today from signals, goals and open decisions."), outcome:l("Sormadan önce bulunan yönetim gündemi","A management agenda discovered before prompting") },
  { id:"prepared", group:"general", title:l("Sizin için hazırlandı","Prepared for you"), summary:l("Bir bulgudan sonraki küçük işi e-posta, teklif isteği, toplantı özeti veya durum güncellemesi olarak önceden hazırlar.","Prepares the next small piece of work, such as an email, quote request, meeting brief or status update."), outcome:l("İncele, düzenle, onayla akışı","Review, edit and approve flow") },
  { id:"entity-360", group:"general", title:l("Varlık 360 ve iş zaman çizgisi","Entity 360 and business timeline"), summary:l("Müşteri, tedarikçi, makine, ürün veya siparişin ölçü, sinyal, araştırma, karar ve görev geçmişini bir araya getirir.","Combines metrics, signals, investigations, decisions and tasks for a customer, supplier, machine, product or order."), outcome:l("Tek varlıkta tam iş bağlamı","Complete business context around one entity") },
  { id:"role-rhythm", group:"general", title:l("Rol ve iş ritmi","Role and operating rhythm"), summary:l("CFO, muhasebeci, üretim yöneticisi veya satış ekibinin günlük, haftalık ve aylık kontrol rutinlerini çalıştırır.","Runs daily, weekly and monthly operating routines for finance, accounting, manufacturing or sales roles."), outcome:l("Yalnız istisna olduğunda dikkat isteyen rutin","Exception-driven operating routines") },
  { id:"smart-assignment", group:"general", title:l("İş girişi ve akıllı atama","Work intake and smart assignment"), summary:l("Yeni işi gerekli yetkinlik, sorumlu, son tarih, bağımlılık ve mevcut yük ile birlikte değerlendirir.","Evaluates incoming work with required skills, ownership, deadline, dependencies and current workload."), outcome:l("Doğru işe doğru sorumlu önerisi","Right owner recommendation for the work") },
  { id:"capacity-control", group:"general", title:l("Kapasite Kontrol Masası","Capacity Control Tower"), summary:l("İnsan, makine, hat, malzeme, ekipman ve zaman penceresini tek kapasite grafında değerlendirir.","Evaluates people, machines, lines, materials, equipment and time windows in one capacity graph."), outcome:l("Uygulanabilir kapasite seçenekleri","Feasible capacity options") },

  { id:"collections", group:"finance", title:l("Akıllı Tahsilat Masası","Smart collections desk"), summary:l("Açık alacak, gecikme, ödeme alışkanlığı, uyuşmazlık ve verilen ödeme sözlerini birlikte izler.","Tracks open receivables, delays, payment behavior, disputes and payment promises together."), outcome:l("Bugün odaklanılacak müşteriler ve beklenen nakit etkisi","Customers to prioritize today and expected cash impact") },
  { id:"reconciliation", group:"finance", title:l("Banka, ERP ve POS Mutabakat Beyni","Bank, ERP and POS reconciliation brain"), summary:l("Banka, POS, kasa ve muhasebe hareketlerini eşleştirir; yalnız gerçekten inceleme gereken farkları öne çıkarır.","Matches bank, POS, cash and accounting movements, surfacing only exceptions that need review."), outcome:l("İstisna odaklı mutabakat kuyruğu","Exception-focused reconciliation queue") },
  { id:"cash-radar", group:"finance", title:l("Günlük Nakit ve Para Radarı","Daily cash radar"), summary:l("Banka, kasa, POS bekleyenleri, çek/senet, tahsilat ve ödemeleri günlük likidite görünümünde birleştirir.","Combines bank, cash, pending POS, instruments, collections and payments into a daily liquidity view."), outcome:l("Bugün para sorunu var mı sorusuna tek cevap","One answer to whether cash needs attention today") },
  { id:"payment-plan", group:"finance", title:l("Akıllı Ödeme Planlayıcısı","Smart payment planner"), summary:l("Nakit tamponu, iskonto, gecikme maliyeti, kritik tedarikçi ve yaklaşan tahsilatı birlikte değerlendirir.","Balances liquidity buffer, discounts, late cost, critical suppliers and expected collections."), outcome:l("Ne zaman ne kadar ödeme yapılmalı önerisi","Recommended payment timing and amount") },
  { id:"e-document", group:"finance", title:l("e-Belge Uyum ve Hazırlık Radarı","e-document readiness radar"), summary:l("Şirket yükümlülüklerini, yaklaşan tarihleri ve eksik kayıt veya evrakları sürekli kontrol eder.","Continuously checks company obligations, upcoming dates and missing records or documents."), outcome:l("Yaklaşan yükümlülük ve açıkların erken görünümü","Early view of obligations and gaps") },
  { id:"invoice-audit", group:"finance", title:l("Akıllı Fatura Denetçisi","Smart invoice auditor"), summary:l("Faturayı sipariş, irsaliye, sözleşme, geçmiş fiyat, miktar, vergi ve mükerrer kayıt bağlamıyla karşılaştırır.","Checks invoices against orders, receipts, contracts, historical price, quantity, tax and duplicate context."), outcome:l("Otomatik doğrulananlar ve öncelikli istisnalar","Auto-cleared invoices and prioritized exceptions") },
  { id:"payment-anomaly", group:"finance", title:l("Şüpheli İşlem ve Ödeme Radarı","Transaction and payment anomaly radar"), summary:l("Mükerrer fatura, sıra dışı tutar, yeni tedarikçi, olağandışı hesap ve davranış sapmalarını ödeme öncesi tarar.","Scans for duplicate invoices, unusual amounts, new vendors, atypical accounts and behavioral deviations before payment."), outcome:l("Ödeme öncesi inceleme sinyali","Pre-payment review signal") },
  { id:"cash-forecast", group:"finance", title:l("13 Haftalık Nakit Tahmini","13-week cash forecast"), summary:l("Bakiye, tahsilat davranışı, borç vadeleri, maaş, vergi ve planlı harcamalardan sürekli nakit görünümü üretir.","Builds a rolling cash view from balances, collection behavior, payables, payroll, tax and planned spend."), outcome:l("Baz, iyimser ve kötü senaryolu likidite görünümü","Base, upside and downside liquidity view") },
  { id:"receivable-risk", group:"finance", title:l("Cari Risk ve Tahsilat Davranışı","Receivables risk and payment behavior"), summary:l("Sipariş sıklığı, ödeme gecikmesi, vade, uyuşmazlık, iade ve toplam riski birlikte değerlendirir.","Combines order frequency, payment delay, terms, disputes, returns and total exposure."), outcome:l("Temerrütten önce bozulan davranışın erken sinyali","Early signal of deteriorating behavior before default") },
  { id:"financial-cause", group:"finance", title:l("Finansal Sebep-Sonuç Grafı","Financial cause-and-effect graph"), summary:l("Marj değişimini hammadde, kur, iskonto, ürün karması, fire, enerji, fazla mesai ve lojistik etkilerine ayırır.","Decomposes margin change across material, FX, discount, mix, scrap, energy, overtime and logistics."), outcome:l("Kâr değişiminin ölçülebilir neden zinciri","Measurable driver chain behind profit change") },
  { id:"close-control", group:"finance", title:l("Ay Sonu Kapanış Kontrol Masası","Month-end close control tower"), summary:l("Mutabakat, tahakkuk, stok, duran varlık, vergi ve inceleme bağımlılıklarını tek kapanış akışında izler.","Tracks reconciliation, accrual, inventory, fixed assets, tax and review dependencies in one close flow."), outcome:l("Kapanış ilerlemesi, kritik yol ve engeller","Close progress, critical path and blockers") },
  { id:"accrual", group:"finance", title:l("Tahakkuk Dedektifi","Accrual detective"), summary:l("Mal kabulü var faturası yok, düzenli hizmet eksik veya dönemsel örüntü kırılmış işlemleri tarar.","Finds received-but-uninvoiced goods, missing recurring services and broken period patterns."), outcome:l("Eksik tahakkuk adayı ve tutar aralığı","Accrual candidate with expected amount range") },
  { id:"working-capital", group:"finance", title:l("Çalışma Sermayesi Avcısı","Working capital hunter"), summary:l("Gecikmiş tahsilat, fazla stok, müşteri vadesi ve tedarikçi şartlarını aynı fırsat havuzunda toplar.","Combines late collections, excess inventory, customer terms and supplier terms in one opportunity pool."), outcome:l("Şirkette serbest bırakılabilecek nakit alanı","Cash that can potentially be released") },
  { id:"profit-leak", group:"finance", title:l("Kâr Kaçağı Dedektörü","Profit leakage detector"), summary:l("İndirim, yanlış fiyat, düşük marjlı müşteri, fire, yeniden işleme, enerji, lojistik ve komisyon kaçaklarını tarar.","Scans discounts, pricing errors, low-margin customers, scrap, rework, energy, logistics and commission leakage."), outcome:l("Görünmeyen kâr kaybı ve kaynakları","Hidden profit loss and its drivers") },
  { id:"fx-position", group:"finance", title:l("Kur ve Döviz Pozisyonu Masası","FX position desk"), summary:l("Dövizli alacak, borç, sipariş, satın alma, kredi ve banka pozisyonlarını zaman içinde birlikte okur.","Reads foreign-currency receivables, payables, orders, purchases, loans and bank positions over time."), outcome:l("Kur senaryolarının nakit ve marj etkisi","Cash and margin impact of FX scenarios") },
  { id:"reporting-difference", group:"finance", title:l("VUK, Yönetim ve TFRS Fark Masası","Statutory, management and IFRS bridge"), summary:l("Vergi görünümü ile yönetim ve finansal raporlama görünümü arasındaki düzeltmeleri ve farkları izler.","Tracks adjustments and differences between statutory, management and financial-reporting views."), outcome:l("Sonuç farkının açıklanabilir köprüsü","Explainable bridge between reporting results") },
  { id:"finance-capacity", group:"finance", title:l("Finans Ekibi İş ve Kapasite Yöneticisi","Finance workload and capacity manager"), summary:l("Kapanış ve günlük işlerde iş yükünü, yetkinliği, görev ayrılığını ve kritik yolu birlikte değerlendirir.","Balances workload, skills, segregation of duties and critical path across close and daily finance work."), outcome:l("Daha dengeli iş dağılımı ve kısa kritik yol","Better workload balance and shorter critical path") },
  { id:"budget-variance", group:"finance", title:l("Bütçe ve Gerçekleşen Sapma Araştırıcısı","Budget variance investigator"), summary:l("Bütçe aşımını fiyat, tüketim, hacim, ürün karması ve diğer katkılara otomatik olarak ayırır.","Automatically decomposes budget variance into price, usage, volume, mix and other contributors."), outcome:l("Sapmanın nedenleri ve müdahale seçenekleri","Variance drivers and intervention options") },
  { id:"cfo-queue", group:"finance", title:l("CFO Karar Kuyruğu","CFO decision queue"), summary:l("Sürekli taramalardan gerçekten finans yöneticisi kararı gerektiren konuları finansal etki ve son tarihle ayırır.","Separates issues that truly require a finance decision, with financial impact and deadline."), outcome:l("Kanıt, seçenek ve varsayımlı karar kartları","Decision cards with evidence, options and assumptions") },
  { id:"assumption-watch", group:"finance", title:l("Finansal Karar Hafızası ve Varsayım Nöbetçisi","Financial decision memory and assumption watch"), summary:l("Önemli kararların dayandığı varsayımları karar sonrasında izler ve bozulduğunda yeniden değerlendirme başlatır.","Monitors assumptions behind important decisions and triggers reassessment when they stop holding."), outcome:l("Yaşayan karar kaydı ve varsayım uyarısı","Living decision record and assumption alert") },

  { id:"plant-today", group:"manufacturing", title:l("Üretim Kontrol Masası","Plant Today control desk"), summary:l("Vardiya, hat ve makine bazında plan, üretim, OEE, fire, duruş, kalite ve termin riskini birlikte izler.","Monitors plan, output, OEE, scrap, downtime, quality and delivery risk by shift, line and machine."), outcome:l("Sabah 30 saniyede tesisin gerçek gündemi","The plant's real agenda in 30 seconds") },
  { id:"loss-tree", group:"manufacturing", title:l("Kayıp Ağacı ve Otomatik Kök Neden Araştırması","Loss tree and automated root-cause investigation"), summary:l("OEE kaybını kullanılabilirlik, performans ve kalite üzerinden makine, ürün, vardiya, bakım ve malzemeye kadar indirir.","Drills OEE loss through availability, performance and quality down to machine, product, shift, maintenance and material."), outcome:l("Kayıbın ölçülebilir neden zinciri","A measurable cause chain behind loss") },
  { id:"delivery-risk", group:"manufacturing", title:l("Plan, Gerçekleşen ve Termin Riski Radarı","Plan, actual and delivery-risk radar"), summary:l("Sipariş planını gerçek üretim hızıyla karşılaştırır ve gecikmeyi son gün yerine önceden fark eder.","Compares order plans with actual production pace and detects lateness before the due date."), outcome:l("Riskteki sipariş, nedeni ve çözüm seçenekleri","At-risk order, cause and response options") },
  { id:"bottleneck", group:"manufacturing", title:l("Akıllı Kapasite ve Darboğaz Masası","Smart capacity and bottleneck desk"), summary:l("Makine, hat, insan, malzeme ve zaman penceresini birlikte değerlendirerek uygulanabilir planlar çıkarır.","Evaluates machines, lines, people, materials and time windows to produce feasible plans."), outcome:l("Darboğazı azaltan uygulanabilir üretim seçenekleri","Feasible production options that relieve bottlenecks") },
  { id:"scrap", group:"manufacturing", title:l("Fire, Hurda ve Yeniden İşleme Dedektifi","Scrap and rework detector"), summary:l("Fire artışını makine, ürün, vardiya, proses ve kalite bağlamında otomatik araştırır.","Investigates scrap increases across machine, product, shift, process and quality context."), outcome:l("Fire artışının kaynağı ve maliyet etkisi","Driver and cost impact of scrap increase") },
  { id:"micro-downtime", group:"manufacturing", title:l("Duruş ve Mikro Duruş Zekâsı","Downtime and micro-stop intelligence"), summary:l("Tek tek küçük görünen duruşların frekans, süre ve üretim değeri üzerinden biriken etkisini bulur.","Finds the accumulated impact of short recurring stops through frequency, duration and production value."), outcome:l("Gizli kapasite kayıplarının sıralaması","Ranked hidden capacity losses") },
  { id:"asset-health", group:"manufacturing", title:l("Bakım Önceliklendirme ve Varlık Sağlığı","Maintenance prioritization and asset health"), summary:l("Arıza örüntüsü, duruş maliyeti, üretim kritikliğini ve bakım iş yükünü birlikte değerlendirir.","Combines failure patterns, downtime cost, production criticality and maintenance backlog."), outcome:l("Doğru zamanda bakım önceliği","Maintenance priority at the right time") },
  { id:"quality-drift", group:"manufacturing", title:l("Kalite Sapması ve İlk Geçiş Başarı Radarı","Quality drift and first-pass-yield radar"), summary:l("Ölçüm henüz sınır dışına çıkmadan kötüleşen eğilimi ve eşlik eden proses koşullarını yakalar.","Detects worsening quality trends and related process conditions before measurements cross limits."), outcome:l("Erken kalite sinyali ve ilişkili koşullar","Early quality signal with related conditions") },
  { id:"resource-efficiency", group:"manufacturing", title:l("Enerji ve Kaynak Başına Üretim Optimizasyonu","Energy and resource productivity optimization"), summary:l("Enerji, su ve diğer kaynakları ürün, makine, vardiya ve üretim miktarına göre normalize eder.","Normalizes energy, water and other resources by product, machine, shift and output."), outcome:l("Birim üretimde verimsiz kaynak kullanımının kaynağı","Source of inefficient resource use per unit") },
  { id:"money-loss-bridge", group:"manufacturing", title:l("Üretim Kaybı Para Köprüsü","Production loss to money bridge"), summary:l("Hız, duruş, fire ve kalite kayıplarını katkı payı ve müşteri teslim etkisiyle finansal dile çevirir.","Translates speed, downtime, scrap and quality losses into contribution and customer-delivery impact."), outcome:l("Operasyon kaybının TL karşılığı","Financial value of operational loss") },

  { id:"rft-dyeing", group:"textile", title:l("İlk Seferde Doğru Boyama Radarı","Right-first-time dyeing radar"), summary:l("Parti, renk ailesi, reçete ve makine bazında ilk seferde doğru sonuç oranını sürekli izler.","Continuously monitors first-time-right outcomes by batch, shade family, recipe and machine."), outcome:l("Düşen başarı oranının yoğunlaştığı koşullar","Conditions where first-time-right performance deteriorates") },
  { id:"recipe", group:"textile", title:l("Akıllı Reçete Öneri ve Düzeltme Masası","Recipe recommendation and correction desk"), summary:l("Geçmiş başarılı partileri kumaş, renk, kimyasal, makine ve müşteri standardıyla birlikte karşılaştırır.","Compares successful historical batches with fabric, shade, chemistry, machine and customer standard."), outcome:l("Daha güvenilir reçete ve düzeltme adayları","More reliable recipe and correction candidates") },
  { id:"batch-preflight", group:"textile", title:l("Parti Ön Kontrolü","Batch preflight"), summary:l("Üretim başlamadan kumaş lotu, makine uyumu, reçete, kimyasal stok, boya lotu, yetkinlik ve termin riskini tarar.","Checks fabric lot, machine fit, recipe, chemical stock, dye lot, skills and delivery risk before production starts."), outcome:l("Hata oluşmadan önce üretim riski","Production risk before the error happens") },
  { id:"shade-root-cause", group:"textile", title:l("Renk Sapması ve Yeniden İşleme Kök Neden Araştırması","Shade deviation and rework root-cause investigation"), summary:l("pH, sıcaklık eğrisi, banyo oranı, boya lotu, makine, kumaş lotu ve geçmiş sonuçları birlikte karşılaştırır.","Compares pH, temperature curve, liquor ratio, dye lot, machine, fabric lot and historical outcomes."), outcome:l("En güçlü renk sapması nedeni adayı","Strongest candidate behind shade deviation") },
  { id:"water-steam", group:"textile", title:l("Su, Buhar ve Enerji Optimizasyonu","Water, steam and energy optimization"), summary:l("Reçete ve makine bazında su, buhar, elektrik, süre ve kalite sonuçlarını birlikte değerlendirir.","Evaluates water, steam, electricity, duration and quality outcomes by recipe and machine."), outcome:l("Kaliteyi koruyarak kaynak tasarrufu alanı","Resource-saving opportunity while protecting quality") },
  { id:"dye-cycle", group:"textile", title:l("Boyama Çevrim Süresi Optimizasyonu","Dyeing cycle-time optimization"), summary:l("Isıtma, soğutma, dozajlama, bekleme, yıkama ve boşta kalma sürelerini başarılı partilerle karşılaştırır.","Compares heating, cooling, dosing, holding, washing and idle time against successful batches."), outcome:l("Gereksiz çevrim süresi ve kapasite fırsatı","Avoidable cycle time and capacity opportunity") },
  { id:"color-sequence", group:"textile", title:l("Renk Sırası ve Makine Çizelgeleme Optimizasyonu","Color sequence and machine scheduling optimization"), summary:l("Termin, renk geçişi, temizlik, makine uyumu, parti büyüklüğü ve reçete ailesini birlikte planlar.","Plans delivery, color transitions, cleaning, machine compatibility, batch size and recipe family together."), outcome:l("Daha az değişim ve daha fazla kullanılabilir kapasite","Fewer changeovers and more usable capacity") },
  { id:"lab-bulk", group:"textile", title:l("Laboratuvardan Seri Üretime Güvenilirlik Masası","Lab-to-bulk reliability desk"), summary:l("Laboratuvar sonucu ile seri üretim reçetesi, makine, banyo oranı ve proses değişkenliğini karşılaştırır.","Compares lab results with bulk recipe, machine, liquor ratio and process variability."), outcome:l("Laboratuvar ile seri üretim arasındaki sapmanın nedeni","Driver of lab-to-bulk deviation") },
  { id:"stenter", group:"textile", title:l("Ramöz ve Terbiye Optimizasyonu","Stenter and finishing optimization"), summary:l("En, gramaj, nem, besleme, sıcaklık, hız, çekme ve enerji değişkenlerini aynı proses penceresinde izler.","Monitors width, weight, moisture, overfeed, temperature, speed, shrinkage and energy in one process window."), outcome:l("Kaliteyi koruyan daha verimli proses penceresi","More efficient process window that protects quality") },
  { id:"textile-customer-risk", group:"textile", title:l("Müşteri Termin ve Kalite Risk Birleştirici","Customer delivery and quality risk bridge"), summary:l("Bir partideki kalite veya yeniden işleme sorununu aynı makineyi bekleyen müşteri siparişlerine bağlar.","Connects a batch quality or rework issue to customer orders waiting on the same machine."), outcome:l("Tek parti sorununun müşteri teslim etkisi","Customer-delivery impact of a single batch issue") },

  { id:"process-stability", group:"plastics", title:l("Proses Kararlılığı Radarı","Process stability radar"), summary:l("Basınç, sıcaklık, çevrim, tork, ağırlık, soğutma ve dozaj gibi proses değişkenlerini normal pencereye göre izler.","Monitors pressure, temperature, cycle, torque, weight, cooling and dosing against the normal process window."), outcome:l("Hatalı parça oluşmadan proses sapması","Process drift before defects appear") },
  { id:"cycle-throughput", group:"plastics", title:l("Çevrim Süresi ve Üretim Hızı Optimizasyonu","Cycle-time and throughput optimization"), summary:l("Enjeksiyon, tutma, soğutma, çıkarma ve boşta kalma adımlarını karşılaştırarak gereksiz süreyi bulur.","Compares injection, holding, cooling, demolding and idle stages to find avoidable time."), outcome:l("Parça başına daha kısa güvenli çevrim","Shorter safe cycle per part") },
  { id:"plastics-scrap", group:"plastics", title:l("Fire ve Red Kök Neden Motoru","Scrap and reject root-cause engine"), summary:l("Kusur tipini malzeme, makine, kalıp, proses parametresi ve operatör bağlamıyla ilişkilendirir.","Relates defect type to material, machine, mold, process parameters and operator context."), outcome:l("Red artışının en güçlü neden kombinasyonu","Strongest driver combination behind reject increase") },
  { id:"drying", group:"plastics", title:l("Malzeme Kurutma Hazırlık Radarı","Material drying readiness radar"), summary:l("Kurutma sıcaklığı, süre, hava akışı ve malzeme geçmişini üretim başlamadan önce kontrol eder.","Checks drying temperature, duration, airflow and material history before production begins."), outcome:l("Üretim öncesi nem ve kalite riski","Moisture and quality risk before production") },
  { id:"dosing", group:"plastics", title:l("Dozaj, Renklendirici ve Kırma Karışım Denetçisi","Dosing, colorant and regrind mix auditor"), summary:l("Ana hammadde, kırma, renklendirici ve katkı oranlarını hedef ve kalite sonucu ile karşılaştırır.","Compares virgin material, regrind, colorant and additive ratios with targets and quality results."), outcome:l("Karışım sapması ile kalite ilişkisinin erken görünümü","Early view of mix deviation and quality relationship") },
  { id:"mold-health", group:"plastics", title:l("Kalıp, Kafa ve Ekstrüder Sağlık Danışmanı","Mold, die and extruder health advisor"), summary:l("Üretim sayacı, bakım geçmişi, çevrim sapması, basınç ve durum verilerini varlık bazında birleştirir.","Combines production count, maintenance history, cycle drift, pressure and condition data by asset."), outcome:l("Yoğun üretimden önce bakım önceliği","Maintenance priority before a busy production window") },
  { id:"energy-shot", group:"plastics", title:l("Enerji Başına Ürün Optimizasyonu","Energy-per-output optimization"), summary:l("Enerjiyi ürün, makine, kalıp ve malzeme kombinasyonuna göre parça veya kilogram başına normalize eder.","Normalizes energy per part or kilogram by product, machine, mold and material combination."), outcome:l("Aynı ürün için gereksiz enerji tüketiminin kaynağı","Source of avoidable energy use for the same product") },
  { id:"changeover", group:"plastics", title:l("Malzeme, Renk ve Kalıp Değişim Optimizasyonu","Material, color and mold changeover optimization"), summary:l("İş sırasını renk, malzeme ailesi, kalıp, temizlik ihtiyacı ve termin etkisine göre değerlendirir.","Evaluates job sequence by color, material family, mold, cleaning needs and delivery impact."), outcome:l("Daha az değişim ve açılan kapasite","Fewer changeovers and released capacity") },
  { id:"recycled-blend", group:"plastics", title:l("Geri Dönüştürülmüş ve Kırma Karışım Optimizasyonu","Recycled and regrind blend optimization"), summary:l("Geri dönüştürülmüş malzeme oranını kalite, proses kararlılığı ve birim maliyetle birlikte değerlendirir.","Evaluates recycled-content ratio together with quality, process stability and unit cost."), outcome:l("Kalite sınırları içinde ekonomik karışım aralığı","Economic blend range within quality limits") },
  { id:"plastics-margin", group:"plastics", title:l("Plastik Birim Maliyet ve Marj Kaçağı Danışmanı","Plastics unit-cost and margin-leak advisor"), summary:l("Hammadde, katkı, fire, makine süresi, işçilik, enerji, kalıp ve duruş etkisini parça veya kilogram maliyetinde birleştirir.","Combines material, additives, scrap, machine time, labor, energy, mold and downtime into cost per part or kilogram."), outcome:l("Teklif marjını bozan gerçek üretim nedeni","Real production driver eroding quoted margin") },
] as const;

export type CapabilityId = (typeof capabilities)[number]["id"];

export const homeCapabilityIds: CapabilityId[] = [
  "today",
  "watch",
  "investigation",
  "decision-desk",
  "scenario-studio",
  "controlled-action",
  "outcome-memory",
  "entity-360",
];
