export type UseCaseId = "executive" | "finance" | "sales" | "manufacturing" | "procurement" | "quality";

export const useCaseLab = {
  eyebrow: { tr: "Gerçek iş senaryoları", en: "Real business scenarios" },
  title: { tr: "Dima farklı ekiplerde neyi, nasıl çözer?", en: "What does Dima solve across different teams, and how?" },
  intro: {
    tr: "Her senaryoda aynı ürün döngüsü çalışır: veri bağlamı korunur, önemli değişim bulunur, nedeni araştırılır, seçenekler hazırlanır ve sonuç aynı şirket hafızasına geri bağlanır. Değişen şey iş alanının varlıkları, kuralları ve karar ölçütleridir.",
    en: "The same product loop runs in every scenario: company context is preserved, important change is detected, causes are investigated, options are prepared and outcomes return to the same company memory. What changes are the entities, rules and decision criteria of the business domain.",
  },
  visualNote: { tr: "Aynı zekâ döngüsü, farklı iş bağlamları.", en: "The same intelligence loop, different business contexts." },
  ready: { tr: "Karara hazır", en: "Decision-ready" },
  visualLabels: {
    signal: { tr: "Sinyal", en: "Signal" },
    reason: { tr: "Neden", en: "Why" },
    decision: { tr: "Karar", en: "Decision" },
    context: { tr: "Bağlam", en: "Context" },
  },
  labels: {
    problem: { tr: "İş problemi", en: "Business problem" },
    detects: { tr: "Dima neyi fark eder?", en: "What does Dima detect?" },
    investigates: { tr: "Nasıl araştırır?", en: "How does it investigate?" },
    recommends: { tr: "Ne hazırlar?", en: "What does it prepare?" },
    result: { tr: "Karar çıktısı", en: "Decision output" },
    data: { tr: "Kullandığı bağlam", en: "Context used" },
  },
  cases: [
    {
      id: "executive",
      layer: { tr: "Yönetim", en: "Executive" },
      title: { tr: "Şirket gündemini rapor aramadan görmek", en: "See the company agenda without hunting through reports" },
      problem: { tr: "Genel müdür finans, satış ve üretimdeki değişimleri ayrı raporlardan takip ediyor; hangi konunun önce ele alınması gerektiği net değil.", en: "Leadership tracks finance, sales and manufacturing changes in separate reports and lacks a clear priority order." },
      detects: { tr: "Teslim riski, nakit baskısı ve marj değişiminin aynı müşteri ve sipariş zincirinde kesiştiğini fark eder.", en: "Detects that delivery risk, cash pressure and margin change intersect around the same customer and order chain." },
      investigates: { tr: "Sipariş, üretim, stok, fatura ve tahsilat ilişkilerini aynı olayda karşılaştırır; yalnız toplam göstergelere bakmaz.", en: "Compares order, production, inventory, invoice and collection relationships in one case instead of relying on totals." },
      recommends: { tr: "Yönetici gündemine tek olay olarak taşır, iş etkisini gösterir ve hangi bölümün hangi adımı sahiplenmesi gerektiğini hazırlar.", en: "Moves it to the executive agenda as one case, shows business impact and prepares ownership across teams." },
      result: { tr: "Önceliklendirilmiş karar gündemi ve açık sorumluluklar", en: "Prioritized decision agenda with explicit ownership" },
      data: { tr: ["Sipariş", "Üretim", "Stok", "Fatura", "Tahsilat"], en: ["Orders", "Production", "Inventory", "Invoices", "Collections"] },
    },
    {
      id: "finance",
      layer: { tr: "Muhasebe ve finans", en: "Accounting and finance" },
      title: { tr: "Tahsilat riskini nakit etkisiyle önceliklendirmek", en: "Prioritize collection risk by cash impact" },
      problem: { tr: "Açık faturalar uzun bir liste oluşturuyor; hangi müşteriye önce müdahale edilmesi gerektiği yalnız tutardan anlaşılmıyor.", en: "Open invoices form a long list, and invoice amount alone does not show which customer needs attention first." },
      detects: { tr: "Ödeme süresi uzayan, sipariş davranışı değişen ve nakit planını etkileyen müşterileri ayırır.", en: "Separates customers with longer payment cycles, changing order behavior and cash-plan impact." },
      investigates: { tr: "Fatura vadesi, banka tahsilatı, sipariş geçmişi, cari hareket ve müşteri davranışını birlikte okur.", en: "Reads invoice due dates, bank collections, order history, receivables movements and customer behavior together." },
      recommends: { tr: "Tahsilat sırasını ve olası takip seçeneklerini 13 haftalık nakit etkisiyle karşılaştırır.", en: "Compares collection priorities and follow-up options through their 13-week cash impact." },
      result: { tr: "Nakit etkisine göre sıralanmış tahsilat planı", en: "Collection plan ranked by cash impact" },
      data: { tr: ["Fatura", "Banka", "Cari", "Sipariş", "Müşteri"], en: ["Invoices", "Banking", "Receivables", "Orders", "Customers"] },
    },
    {
      id: "sales",
      layer: { tr: "Satış", en: "Sales" },
      title: { tr: "Ciro normal görünürken marj kaçağını bulmak", en: "Find margin leakage while revenue still looks normal" },
      problem: { tr: "Toplam ciro hedefe yakın olduğu için ürün karması ve müşteri davranışındaki değişim geç fark ediliyor.", en: "Revenue remains close to target, hiding changes in product mix and customer behavior." },
      detects: { tr: "Düşük marjlı ürünlerin payının arttığını ve değişimin belirli müşteri gruplarında yoğunlaştığını fark eder.", en: "Detects a higher share of low-margin products concentrated in specific customer groups." },
      investigates: { tr: "Fiyat, hacim, ürün karması, indirim, maliyet ve tahsilat ilişkilerini birbirinden ayırır.", en: "Separates price, volume, product mix, discount, cost and collection effects." },
      recommends: { tr: "Hangi müşteri ve ürünlerde fiyat, karma veya hacim müdahalesinin daha anlamlı olduğunu senaryo olarak hazırlar.", en: "Prepares scenarios showing where price, mix or volume intervention is more meaningful." },
      result: { tr: "Marj kaybının nedenleri ve müşteri bazlı seçenekler", en: "Drivers of margin loss with customer-level options" },
      data: { tr: ["Müşteri", "Ürün", "Fiyat", "Maliyet", "Sipariş"], en: ["Customer", "Product", "Price", "Cost", "Order"] },
    },
    {
      id: "manufacturing",
      layer: { tr: "Üretim", en: "Manufacturing" },
      title: { tr: "OEE düşüşünü duruş, sipariş ve bakım bağlamında açıklamak", en: "Explain OEE loss through downtime, orders and maintenance" },
      problem: { tr: "Hat performansı düşüyor fakat tek OEE değeri sorunun hız, duruş, kalite veya ürün karmasından mı geldiğini göstermiyor.", en: "Line performance drops, but one OEE value does not explain whether the cause is speed, downtime, quality or product mix." },
      detects: { tr: "Kayıbın belirli makine, sipariş ve vardiyalarda tekrar ettiğini fark eder.", en: "Detects that the loss repeats around specific machines, orders and shifts." },
      investigates: { tr: "Kullanılabilirlik, performans ve kaliteyi bakım geçmişi, ürün değişimi ve sipariş terminiyle karşılaştırır.", en: "Compares availability, performance and quality with maintenance history, changeovers and order due dates." },
      recommends: { tr: "Bakımı öne alma, üretim sırasını değiştirme veya mevcut planı koruma seçeneklerini termin ve maliyet etkisiyle karşılaştırır.", en: "Compares maintenance, resequencing and keep-plan options by delivery and cost impact." },
      result: { tr: "Kanıtlı kök neden adayları ve operasyon seçenekleri", en: "Evidence-backed cause candidates and operational options" },
      data: { tr: ["OEE", "Duruş", "Bakım", "Sipariş", "Vardiya"], en: ["OEE", "Downtime", "Maintenance", "Orders", "Shifts"] },
    },
    {
      id: "procurement",
      layer: { tr: "Satın alma", en: "Procurement" },
      title: { tr: "En ucuz fiyat yerine toplam maliyeti optimize etmek", en: "Optimize total cost instead of unit price alone" },
      problem: { tr: "Tedarikçi değerlendirmesi birim fiyata sıkışıyor; termin, kalite, stok ve nakit etkisi ayrı dosyalarda kalıyor.", en: "Supplier evaluation collapses into unit price while lead time, quality, inventory and cash effects stay in separate files." },
      detects: { tr: "Daha düşük fiyatlı alternatifin termin ve ödeme koşullarıyla birlikte gerçek bir fırsata dönüşebileceğini fark eder.", en: "Detects when a lower-price alternative may become a real opportunity after lead time and payment terms are included." },
      investigates: { tr: "Fiyat geçmişi, teslim performansı, kalite sonucu, mevcut stok, tüketim planı ve ödeme vadesini birlikte okur.", en: "Reads price history, delivery performance, quality, inventory, consumption plan and payment terms together." },
      recommends: { tr: "Toplam maliyet, stok ve nakit etkisine göre alternatifleri karşılaştırır; kalite eşiği korunuyorsa geçiş planı hazırlar.", en: "Compares alternatives by total cost, inventory and cash impact, then prepares a switch plan if quality thresholds hold." },
      result: { tr: "Toplam maliyete göre tedarikçi kararı", en: "Supplier decision based on total cost" },
      data: { tr: ["Tedarikçi", "Fiyat", "Termin", "Stok", "Kalite", "Ödeme"], en: ["Supplier", "Price", "Lead time", "Inventory", "Quality", "Payment"] },
    },
    {
      id: "quality",
      layer: { tr: "Kalite", en: "Quality" },
      title: { tr: "Tekrarlayan kusurun ortak koşulunu bulmak", en: "Find the common condition behind a recurring defect" },
      problem: { tr: "Kusur kayıtları tek tek inceleniyor; lot, makine, reçete ve vardiya arasındaki ortak örüntü gözden kaçabiliyor.", en: "Defect records are reviewed individually and a common pattern across lot, machine, recipe and shift can be missed." },
      detects: { tr: "Aynı kusurun belirli lot ve makine eşleşmelerinde normalden daha sık oluştuğunu fark eder.", en: "Detects that the same defect appears more often in specific lot and machine combinations." },
      investigates: { tr: "Kalite sonucu, lot, makine, proses koşulu, yeniden işleme ve müşteri geri bildirimlerini aynı zaman çizgisinde karşılaştırır.", en: "Compares quality result, lot, machine, process conditions, rework and customer feedback on the same timeline." },
      recommends: { tr: "En güçlü neden adayını doğrulamak için dar kapsamlı kontrol adımı ve izleme eşiği hazırlar.", en: "Prepares a narrow validation step and monitoring threshold for the strongest cause candidate." },
      result: { tr: "Tekrarlanabilir kontrol planı ve izlenecek eşik", en: "Repeatable validation plan and monitoring threshold" },
      data: { tr: ["Kalite", "Lot", "Makine", "Proses", "Yeniden işleme"], en: ["Quality", "Lot", "Machine", "Process", "Rework"] },
    },
  ] as const,
} as const;
